create table Person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100) NOT NULL,
    age   int,
    email varchar(200)
);
INSERT INTO Person(name, age, email)
VALUES ('Tom', 25, 'tom@mail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 31, 'bob1@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 53, 'bob2@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 20, 'bob3@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Katy', 14, 'katy@gmail.com');

CREATE TABLE Item
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int          REFERENCES Person (id) ON DELETE SET NULL,
    item_name varchar(100) NOT NULL
);

INSERT INTO Item(person_id, item_name)
VALUES (1, 'Airpods');
INSERT INTO Item(person_id, item_name)
VALUES (1, 'Playstation');
INSERT INTO Item(person_id, item_name)
VALUES (1, 'TV');

-- Просто дата без точного времени
ALTER TABLE Person
    ADD COLUMN date_of_birth DATE;

-- Точное время
-- Значение timestamp сохраняются в секундах до и после полуночи 1 января 2000г
ALTER TABLE Person
    ADD COLUMN created_at TIMESTAMP;

ALTER TABLE Person
    ADD COLUMN mood int; -- int because EnumType.ORDINAL

ALTER TABLE Person
    DROP COLUMN mood;

ALTER TABLE Person
    ADD COLUMN mood varchar; -- varchar because EnumType.STRING

select *
from Person;

drop table Person;
drop table Item;