create table Person
(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(100) NOT NULL,
    age   int,
    email varchar(200)
);
INSERT INTO Person(name, age, email)
VALUES ('Tom', 25, 'tom@mail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 31, 'bob1@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 53, 'bob2@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Bob', 20, 'bob3@gmail.com');
INSERT INTO Person(name, age, email)
VALUES ('Katy', 14, 'katy@gmail.com');

CREATE TABLE Item
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int          REFERENCES Person (id) ON DELETE SET NULL,
    item_name varchar(100) NOT NULL
);

INSERT INTO Item(person_id, item_name)
VALUES (1, 'Airpods');
INSERT INTO Item(person_id, item_name)
VALUES (1, 'Playstation');
INSERT INTO Item(person_id, item_name)
VALUES (1, 'TV');

select *
from Person;

drop table Person;
drop table Item;