CREATE
database project1_db;

drop table Book;
drop table Person;
create table Person
(
    id            int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(100) UNIQUE NOT NULL,
    year_of_birth int CHECK ( year_of_birth > 1900 )
);
create table Book
(
    id                 int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title              varchar(100) NOT NULL,
    author             varchar(60)  NOT NULL,
    person_id          int          REFERENCES Person (id) ON DELETE SET NULL,
    year_of_publishing int CHECK ( year_of_publishing > 1500 )
);

SELECT *FROM book;